[colors.primary]
background = "#000000"
foreground = "#94a8a8"

[colors.cursor]
text = "#000000"
cursor = "#b3caca"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#b3caca"

[colors.search.matches]
foreground = "#000000"
background = "#8f784b"

[colors.search.focused_match]
foreground = "#000000"
background = "#8c4343"

[colors.footer_bar]
foreground = "#000000"
background = "#94a8a8"

[colors.selection]
text = "{{ selection_foreground }}"
background = "{{ selection_background }}"

[colors.normal]
black = "#0d1011"
red = "#8c4343"
green = "#4a7856"
yellow = "#8f784b"
blue = "#48678c"
magenta = "#7d5482"
cyan = "#488282"
white = "#667a7a"

[colors.bright]
black = "#2a3233"
red = "#d16969"
green = "#76a882"
yellow = "#c9a96e"
blue = "#6b8eb3"
magenta = "#a87eb0"
cyan = "#65b3b3"
white = "#a3b8b8"
