# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#000000"

# Main text color
theme[main_fg]="#94a8a8"

# Title color for boxes
theme[title]="#94a8a8"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#4a7a7a"

# Background color of selected item in processes box
theme[selected_bg]="#2a3233"

# Foreground color of selected item in processes box
theme[selected_fg]="#4a7a7a"

# Color of inactive/disabled text
theme[inactive_fg]="#2a3233"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#94a8a8"

# Background color of the percentage meters
theme[meter_bg]="#2a3233"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#94a8a8"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#7d5482"
theme[mem_box]="#4a7856"
theme[net_box]="#8c4343"
theme[proc_box]="#4a7a7a"

# Box divider line and small boxes line color
theme[div_line]="#2a3233"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#4a7856"
theme[temp_mid]="#8f784b"
theme[temp_end]="#8c4343"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#488282"
theme[cpu_mid]="#48678c"
theme[cpu_end]="#7d5482"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#7d5482"
theme[free_mid]="#48678c"
theme[free_end]="#488282"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#48678c"
theme[cached_mid]="#488282"
theme[cached_end]="#7d5482"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#8f784b"
theme[available_mid]="#8c4343"
theme[available_end]="#8c4343"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#4a7856"
theme[used_mid]="#488282"
theme[used_end]="#48678c"

# Download graph colors (Peach -> Red)
theme[download_start]="#8f784b"
theme[download_mid]="#8c4343"
theme[download_end]="#8c4343"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#4a7856"
theme[upload_mid]="#488282"
theme[upload_end]="#48678c"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#488282"
theme[process_mid]="#48678c"
theme[process_end]="#7d5482"
