foreground #94a8a8
background #000000
selection_foreground {{ selection_foreground }}
selection_background {{ selection_background }}

cursor #b3caca
cursor_text_color #000000

active_border_color #4a7a7a
active_tab_background #4a7a7a

color0 #0d1011
color1 #8c4343
color2 #4a7856
color3 #8f784b
color4 #48678c
color5 #7d5482
color6 #488282
color7 #667a7a
color8 #2a3233
color9 #d16969
color10 #76a882
color11 #c9a96e
color12 #6b8eb3
color13 #a87eb0
color14 #65b3b3
color15 #a3b8b8
